name: C/C++ Ubuntu CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: submodules
      run: git submodule update --init --recursive

    - name: Setup Cpp (C++ / C)
      # You may pin to the exact commit or the version.
      # uses: aminya/setup-cpp@290824452986e378826155f3379d31bce8753d76
      uses: aminya/setup-cpp@v0.37.0
      with:
        # The compiler to use and its optional version separated by - e.g. llvm-13.0.0
        compiler: gcc-13
        # The CPU architecture
        architecture: x64
        # The llvm version to install
        llvm: # optional
        # The gcc version to install
        gcc: 13
        # The msvc version to install
        msvc: # optional
        # If should run vcvarsall?
        vcvarsall: # optional
        # The cmake version to install.
        cmake: # optional
        # The ninja version to install.
        ninja: # optional
        # The conan version to install.
        make: # optional
        # The task version to install.
        task: # optional
        # The vcpkg version to install.
        vcpkg: # optional
        # The gcovr version to install.
        gcovr: # optional
        # The python version to install.
        python: # optional
        # The ccache version to install.
        ccache: # optional
        # The sccache version to install.
        sccache: # optional
        # The cppcheck version to install.
        cppcheck: # optional
        # The clang-tidy version to install.
        clangtidy: # optional
        # The clang-format version to install.
        clangformat: # optional
        # The opencppcoverage version to install.
        opencppcoverage: # optional
        # The kcov version to install.
        kcov: # optional
        # The 7z version to install.
        sevenzip: # optional
        # The nala version to install ("" or "legacy").
        nala: # optional
        # The powershell version to install.
        powershell: # optional
        # The timeout for installation of one tool (in minutes).
        timeout: # optional, default is 20

    - name: create build directory
      run: mkdir build

    - name: create build project
      run: cmake -S . -B ./build

    - name: build project
      run: cmake --build ./build
